### ISSUE TITLE
Guide button

### ISSUE THREAD

**Issue by DarKcyde0** [shauleiz/vXboxInterface#2]
Need access to the guide button please!

#define XINPUT_GAMEPAD_GUIDE 0x0400

**Comment by shauleiz** [comment]
I don't think it is documented. Do you have link?

**Comment by shauleiz** [comment]
I don't think it is documented. Do you have link?

**Comment by DarKcyde0** [comment]
It's undocumented by MS, for some reason.  There's code all over the web that figured it out.  

https://autohotkey.com/board/topic/35848-xinput-xbox-360-controller-api/page-4 has it in their Xinput lib.

You'd have to add it to your Xinput.h, or just manually call 0x0400 for the guide button.

**Comment by shauleiz** [comment]
Made the change and published.
Did **not* test.
Please approve so we can make it official.
Thank you!

**Comment by DarKcyde0** [comment]
I won't have time to finish my feeder until the weekend.  Thanks for compiling a release!

**Comment by shauleiz** [comment]
Take your time. I will be on vacation until the 20th

**Comment by djlastnight** [comment]
I already mentioned that in issue #1, anyway glad to see the change now..

**Comment by DarKcyde0** [comment]
Got my feeder functional, at least for buttons.  Guide button works.  It brings up steam in windows, works inside Oculus home, and calls up oculus menu from within games.  Very happy, thanks man!

**Comment by shauleiz** [comment]
Sure, no problem.
Closing the issue and publishing the release.
Thank **you**
