### ISSUE TITLE
Xbox one controller

### ISSUE THREAD

**Issue by colhemm** [shauleiz/vXboxInterface#3]
Would it be posable to make this Xbox one controller compatible? After a road traffic accident, I've been unable to hold the Xbox one controller for my Oculus rift. To be able to map the Xbox one controller to any joystick or keyboard with this would be a massive help.

Thanks
Colhemm

**Comment by shauleiz** [comment]
Please forgive me but I am not sure I understand.
Do you mean that vXboxInterface is not xBox One compatible or you have a problem with Oculus.
You also say that you cannot hold the Xbox controller but you wish to map it to other devices.
I am sure I am missing something.

**Comment by colhemm** [comment]
Sorry if I sound very naive but I'm not a coder. if this can control an Xbox one controller that's great.

I can hold a joystick but i can't hold a joypad and i need to control the buttons with my voice. The Oculus Rift will only let you use an Xbox one controller so that's me out. 

A great guy called `` [billyisms](https://github.com/billyisms) helped me setup something with XOutput, vJoy and UCR. It really helped but it only creates an Xbox 360 controller.

**Comment by shauleiz** [comment]
OK. Let me ask around.

**Comment by shauleiz** [comment]
I consulted the owner of the driver behind XOutput.
He thinks that changing the solution to emulate an XB1 controller needs changing the driver, which is bad because changing a driver is a serious matter.
The good news is that he considers this task as important.
You can approach him directly here: https://github.com/nefarius/ViGEm

**Comment by colhemm** [comment]
Thank you so much for your help shauleiz it's really appreciated.

Colhemm
