### ISSUE TITLE
GetNumEmptyBusSlots / PlugIn both fail with WinApi Error 87 (Invalid Parameter)

### ISSUE THREAD

**Issue by mode777** [shauleiz/vXboxInterface#5]
Hello everyone, 
I'm trying to get the Test project to work  but it keeps failing.
I installed just the windows service with the SCP Driver Installer v. 1.6.238.16010 and the isVBusExists() returns true.
However GetNumEmptyBusSlots fails at line 57 with a call to:
``` DeviceIoControl(g_hBus, IOCTL_BUSENUM_EMPTY_SLOTS, nullptr, 0, output, 1, &trasfered, nullptr) ```

As well es a call to PlugIn which similarily fails at DeviceIoControl.

GetLastError gives me code 87 which apparently means InvalidParameter.
I'm on Windows 10 64bit btw.

Maybe I'm missing something?

**Comment by shauleiz** [comment]
Use SCP v1.7.1.2

**Comment by mode777** [comment]
Thanks for the quick reply.

I tried ScpToolkit v1.7.277.16103-BETA and wiped the old installation before with the tool provided.
Still I get the same error.

I couldn't find SCP 1.7.1.2 there doesn't seem to be such a release, at least on github.
