### ISSUE TITLE
ScpVBus compatibility

### ISSUE THREAD

**Issue by evgen-y2k** [shauleiz/vXboxInterface#6]
Hi. I use vXboxinterface in my project but surprisely I see that vXboxinterface can't work with original Nefarius ScpVBus from ScpToolkit project (https://github.com/nefarius/ScpVBus).  I used ScpVBus from your repository when created my project. After that I installed ScpToolkit and my application can't work. Do you can help me? Realy your xVboxinterface not compatible with Nefarius ScpVBus or I made something not correct?

**Comment by shauleiz** [comment]
No, it is not compatible.
Nefarius, has practically stopped developing ScpVBus and moved to ViGEm.
You need to ask him if how to interface with his bus.

**Comment by evgen-y2k** [comment]
Ok. Thank so much.
