### ISSUE TITLE
Get trigger lvl & pov position from virtual device

### ISSUE THREAD

**Issue by goldstar2154** [shauleiz/vXboxInterface#8]
Hello, thx for this api.
Is it possible to make API functions thats can send back device analog data (like trigger position, X/Y axis and others). This will be usefull to make more comfortable discrete key to analog conversion.
At this moment i save this data into variables, but this is not good practice i think)
For example:
`BOOL GetTriggerL(UINT UserIndex, BYTE& triggerLvl);`
usage in code:
```
...
BYTE triggerL = 0;
GetTriggerL(1, triggerL) ;
triggerL += 1;
SetTriggerL(1, triggerL);
...
```

Best regards.

**Comment by shauleiz** [comment]
Development on this project is discontinued.
If you are interested in work with virtual XBox devices - please refer to [ViGem](https://github.com/nefarius/ViGEm).
