### ISSUE TITLE
No license for release

### ISSUE THREAD

**Issue by jguerin** [shauleiz/vXboxInterface#9]
Hi @shauleiz ,

We're looking to leverage this code for some internal testing that we're doing, but I cannot find a license agreement for this repository. Would you mind helping me understand how you're licensing this code? :)

Cheers,

Jonathan

**Comment by shauleiz** [comment]
vXboxInterface is Open Source and free.
Use it as you wish (at your own risk).
No need to pay anything. Enjoy.

**Comment by jguerin** [comment]
@shauleiz - completely understand! :) However, many businesses that might want to use binaries or source from an Open Source project would need an explicit license agreement in order to use the work.

Github provides an easy to use [site ](https://choosealicense.com/)that allows you to pick a license that meets the goals of your project. You can read more about it [here](https://help.github.com/articles/licensing-a-repository/). 

We're unable to use your awesome code without a license. :(

**Comment by shauleiz** [comment]
I see. This is the first time people refuse to believe me that it is free...
Please help me, which license do you think is the appropriate one. I am not a lawyer and surely have no means nor intention to sue you...

**Comment by jguerin** [comment]
@shauleiz the question is not about whether your repository is free or not - we're very grateful that you have spent the time and effort to put this together for use by anyone! :) The concern that many businesses have will be how to understand how the software copyright is licensed, and therefore how it can be used.

You can read more about the impact not having a license [here](https://choosealicense.com/no-license/).

Github's [license chooser](https://choosealicense.com/) is actually quite useful in providing guidance on picking the right license for what you want. I'd highly recommend that you check it out! :)

**Comment by jguerin** [comment]
(for full disclosure, I work for Microsoft) :)

**Comment by shauleiz** [comment]
We all do, one way or the other :)

**Comment by shauleiz** [comment]
I added the MIT license. Hope this meets your needs and that I did it correctly.
BTW, my much more interesting project is vJoy (https://github.com/shauleiz/vJoy) which will soon be unloadable since W10 1703 seems to be unhappy with its certificate.
If you can pull strings (I know, you cannot. I worked for Intel 30 years ago) to sign vJoy correctly zillions of users will be kissing your hand.

**Comment by jguerin** [comment]
Thanks so much for adding that, greatly appreciated!

For vJoy, you should be able get your driver signed if you have the right certificate issued. You can read more about it [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/driver-signing).
